library_management_system/Bookmodule/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'Bookmodule'
urlpatterns = [
   path('addBook/',views.addBook,name='addBook'),
   path('issueBook/',views.issueBook,name='issueBook'),
   path('returnBook/',views.returnBook,name='returnBook'),
   path('removeBook/',views.removeBook,name='removeBook'),
   path('showFine/',views.showFine,name='showFine'),
   path('profile/',views.profile,name='profile'),
] 

library_management_system/library_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
   path('admin/', admin.site.urls),
   path('',include("loginmodule.urls")),
   path('Bookmodule/',include("Bookmodule.urls")),
   
]

library_management_system/loginmodule/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

app_name = 'loginmodule'
urlpatterns = [
   path('',views.home,name='home'),
   path('register/',views.register,name='register'),
   path('login/',views.login,name='login'),
   path('welcome/',views.welcome,name='welcome'),
   path('logout/',views.logout,name='logout'),
]

library_management_system/loginmodule/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Reader(models.Model):
    username = models.CharField(primary_key=True,max_length=20)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField(max_length=50)
    password = models.CharField(max_length=20)

library_management_system/loginmodule/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.models import User,auth
from .models import Reader

superuser_username = "admin"
superuser_password = "admin" 

def login(request):
    if request.session.get('username') == None:
        return render(request,'loginmodule/login.html')
    else:
        return redirect('loginmodule:welcome')

def register(request):
    if request.method == "POST" :
        username=request.POST['username']
        password1=request.POST['password']
        password2=request.POST['repassword']
        email = request.POST['email']
        first_name = request.POST['fname']
        last_name = request.POST['lname']
         #check password and repassword are same or not
        if password1 == password2:
            #if both are same then forward procced
            if Reader.objects.filter(username = username).exists():
                messages.error(request,'username already taken')
                return render(request,'loginmodule/register.html')
            elif Reader.objects.filter(email = email).exists():
                messages.error(request,'email already taken')
                return render(request,'loginmodule/register.html')
            else :
                user = Reader(username = username , password = password1,
                              first_name = first_name , last_name = last_name,
                                email = email)
                user.save()
                return redirect(reverse("loginmodule:login"))
                
        #if passwords are not match then again render register pagr                               
        else:
            messages.error(request,"password does not match")
            return render(request,'loginmodule/register.html')
    else:
         return render(request,'loginmodule/register.html')

def home(request):
    if request.session.get('username') == None:
        return render(request,'loginmodule/home.html')
    else:
        return redirect(reverse("loginmodule:welcome"))

def welcome(request):
    if request.session.get('username') == None:
        if request.method == "POST":
            # analyse the form
            username=request.POST['username']
            password=request.POST['password']
            try:
                superUser = request.POST['superuser']
            except:
                superUser = None
            if superUser == "superuser":
                if username == superuser_username and password == superuser_password:
                    request.session['superuser'] = True
                    # return redirect(reverse("loginmodule:welcome"))
                    return render(request,"loginmodule/welcome.html")
                else:
                    messages.error(request,"You'r not authorize")
                    return render(request,"loginmodule/login.html")
            else:
                #check user is register or not
                if Reader.objects.filter(username = username).exists() and Reader.objects.filter(password = password).exists():
                    request.session['username'] = username
                    return render(request,'loginmodule/welcome.html')
                #user is  register then value of user is not None
                else:
                    #login access to user
                    messages.error(request,"Invalid username or password")
                    return redirect(reverse("loginmodule:login"))
        else:
            # first login
            return redirect(reverse("loginmodule:login"))
    else:
        return render(request,'loginmodule/welcome.html')
    
def logout(request):
    if 'username' in request.session:
        del request.session['username']
    if 'superuser' in request.session:
        del request.session['superuser']
    messages.success(request,'You are logged out!')
    return redirect(reverse('loginmodule:login'))

library_management_system/loginmodule/templates/loginmodule/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	{% block style %}
		<!-- Style -->
	{% endblock style %}

	{% block title %}

	{% endblock title %}

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

	<style>
		body{
			margin: 0;
			padding: 0;
			background-image: url('{% static "book4.jpg"%}');
			background-repeat: no-repeat;
			background-size: cover;
		}
	</style>
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'loginmodule:home' %}">Library</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavAltMarkup">
	      <div class="navbar-nav">

	      	{% block navbarLinks %}
		        
	      	{% endblock navbarLinks %}

	      </div>
	    </div>
	  </div>
	</nav>

	{% if messages %}
	{% for message in messages%}
	{% if message.tags == 'error' %}
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
	{% else %}
	<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
	{% endif %}
	<strong>
	    {{ message }}
	</strong>
	{%endfor%}
	<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
	{% endif %}

	{% block body %}
		<!-- Body -->
	{% endblock body %}

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

library_management_system/loginmodule/templates/loginmodule/home.html
{% extends 'loginmodule/base.html' %}
{% load static %}

{% block title %}
	<title>Home</title>
{% endblock title %}

{% block body %}
	<div class="quote">
		<h1>Library Management System</h1>
		<p>"One Best Book is equal to Hundred Good Friends, One Good Friend is equal to a Library" </p> 
		<div class="a">- Dr. A.P.J. Abdul Kalam</div>
	</div>
{% endblock body %}

{% block navbarLinks %}
	<a class="nav-link" href="{% url 'loginmodule:register' %}">Register</a>
	<a class="nav-link" href="{% url 'loginmodule:login' %}">Login</a>
{% endblock navbarLinks %}

library_management_system/loginmodule/templates/loginmodule/login.html
{% extends 'loginmodule/base.html' %}
{% load static %}

{% block title %}
	<title>Login</title>
{% endblock title %}
		
{% block body %}
	<form action='/welcome/' method="POST" class="login-form">
		{% csrf_token %}
		<b>
			<div class="mb-3">
				<label class="form-label">Username</label>
				<input type="text" class="form-control" name="username">
			</div>
			<div class="mb-3">
				<label class="form-label">Password</label>
				<input type="password" class="form-control" name="password">
			</div>
			<div class="mb-3 form-check">
				<input type="checkbox" class="form-check-input" value="superuser" name="superuser">
				<label class="form-check-label">Superuser</label>
			</div>
		</b>
		<button type="submit" class="btn btn-primary">Login</button>
	</form>
{% endblock body %}

{% block navbarLinks %}
	<a class="nav-link" href="{% url 'loginmodule:register' %}">Register</a>
{% endblock navbarLinks %}

{% block style %}
<style>
	.login-form input {
		background: transparent;
	}

	.login-form{
		width: 320px;
		height: 420px;
		top: 50%;
		left: 20%;
		position: absolute;
		transform: translate(-50%,-50%);
		box-sizing: border-box;
    }
</style>	
{% endblock style %}

library_management_system/loginmodule/templates/loginmodule/register.html
{% extends 'loginmodule/base.html' %}
{% load static %}

{% block title %}
	<title>Register</title>
{% endblock title %}
		
{% block body %}
	<form action="" method="POST" class="Register-form">
		<h1>Registration here</h1>
		{% csrf_token %}
		
		<div class="mb-3">
		<b>
				<label class="form-label">Username</label>
				<input type="text" class="form-control" name="username" required>
			</div>
			<div class="mb-3">
				<label class="form-label">Firstname</label>
				<input type="text" class="form-control" name="fname" required>
			</div>
			<div class="mb-3">
				<label class="form-label">Last name</label>
				<input type="text" class="form-control" name="lname" required>
			</div>
			<div class="mb-3">
				<label class="form-label">E-mail Id</label>
				<input type="email" class="form-control" name="email" required>
			</div>
			<div class="mb-3">
				<label class="form-label">Password</label>
				<input type="password" class="form-control" name="password" required>
			</div>
			<div class="mb-3">
				<label class="form-label">Confirm Password</label>
				<input type="password" class="form-control" name="repassword" required>
			</div>
			
		</b>
		<button type="submit" class="btn btn-primary">Register</button>
	</form>
{% endblock body %}

{% block navbarLinks %}
	<a class="nav-link" href="{% url 'loginmodule:login' %}">login</a>
{% endblock navbarLinks %}

{% block style %}
<style>
	.Register-form input {
		background: transparent;
	}

	.Register-form{
		width: 320px;
		height: 420px;
		top: 50%;
		left: 20%;
		position: absolute;
		transform: translate(-50%,-50%);
		box-sizing: border-box;
    }
	h1{
		margin: 0;
		padding: 0 0 30px;
		text-align: center;
		font-size: 38px;
	}
</style>	
{% endblock style %}

library_management_system/loginmodule/templates/loginmodule/welcome.html
{% extends 'loginmodule/base.html' %}
<title>library management system</title>

{% block title %}
	<title>Welcome</title>
{% endblock title %}

{% block navbarLinks %}
	{% if request.session.superuser %}
		<a class="nav-link" href="{% url 'Bookmodule:addBook' %}">Add book</a>
		<a class="nav-link" href="{% url 'Bookmodule:removeBook' %}">Remove book</a>
	{% else %}
		<a class="nav-link" href="{% url 'Bookmodule:issueBook' %}">Issue book</a>
		<a class="nav-link" href="{% url 'Bookmodule:returnBook' %}">Return book</a>
		<a class="nav-link" href="{% url 'Bookmodule:showFine' %}">Show fine</a>
		<a class="nav-link" href="{% url 'Bookmodule:profile' %}">profile</a>
	{% endif %}
		<a class="nav-link" href="{% url 'loginmodule:logout' %}">Logout</a>
{% endblock navbarLinks %}